import discord
from discord.ext import commands

class Spam(commands.Cog):
    def __init__(self, client):
        self.client = client

    @commands.command()
    async def spam(self, ctx):
        if ctx.author.id == 977993035717681252 or 745717254678904862:
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
            await ctx.reply('SPAM')
        else:
            await ctx.reply('NOOOOOO!!!! LOL')

def setup(client):
    client.add_cog(Spam(client))